import { Service } from "./types";

export const MOCK_SERVICES: Service[] = [
  {
    id: "s1",
    reference: "SERV-CCTV-INSTALL-CAM",
    name: "Installation caméra IP",
    family: "CCTV",
    unit: "Caméra installée",
    internalCost: 2000,
    sellingPrice: 4500,
    margin: 2500,
    marginRate: 125,
    status: "Actif",
    description: "Pose, orientation, raccordement et test d'une caméra IP.",
    estimatedDuration: "2 heures",
    conditions:
      "Nécessite la présence de câblage à l'emplacement d'installation.",
    requiredSkills: [
      "Installation CCTV",
      "Habilitation électrique BR",
      "Travail en hauteur",
    ],
    prerequisites: [
      "Zone dégagée",
      "Nacelle si hauteur > 3m",
      "Plan d'implantation validé",
    ],
    executionSteps: [
      "Vérification du matériel",
      "Pose du support de fixation",
      "Installation de la caméra",
      "Raccordement RJ45 et alimentation",
      "Orientation de l'objectif",
      "Test de connectivité et d'image",
    ],
    associatedEquipment: [
      "Caméra IP",
      "Support mural/plafond",
      "Boîte de jonction",
      "Visserie",
    ],
    requiredDocuments: [
      "Plan d'implantation",
      "Fiche technique de la caméra",
      "Attestation de sécurité (hauteur)",
    ],
    qualityCheckpoints: [
      "Solidité de la fixation",
      "Étanchéité des connecteurs",
      "Angle de vue optimal",
      "Focale réglée",
    ],
    createdAt: "2025-01-15T09:00:00Z",
    lastUsed: "2026-05-18T14:30:00Z",
    usageCount: 145,
    lastUpdatedBy: "Admin. technique",
  },
  {
    id: "s2",
    reference: "SERV-CCTV-CONFIG-NVR",
    name: "Configuration NVR",
    family: "CCTV",
    unit: "Forfait",
    internalCost: 5000,
    sellingPrice: 12000,
    margin: 7000,
    marginRate: 140,
    status: "Actif",
    description:
      "Paramétrage initial, création des utilisateurs, configuration des disques et enregistrements.",
    estimatedDuration: "4 heures",
    conditions:
      "Le réseau doit être opérationnel, adresses IP dédiées disponibles.",
    requiredSkills: ["Administration système CCTV", "Réseau TCP/IP"],
    prerequisites: [
      "Tableau IP défini",
      "Accès admin au réseau",
      "Disques durs installés au préalable",
    ],
    executionSteps: [
      "Mise à jour du firmware",
      "Formatage et configuration RAID (si applicable)",
      "Assignation de l'adresse IP fixe",
      "Ajout des caméras au NVR",
      "Configuration des profils d'enregistrement (mouvement/continu)",
      "Création des comptes opérateurs",
    ],
    associatedEquipment: ["NVR", "Disque dur", "Onduleur", "Moniteur"],
    requiredDocuments: [
      "Fiche des paramètres réseau",
      "Charte de sécurité (mots de passe)",
    ],
    qualityCheckpoints: [
      "Caméras toutes connectées",
      "Enregistrement fonctionnel",
      "Test de relecture réussi",
      "Accès distant vérifié",
    ],
    createdAt: "2025-02-10T11:00:00Z",
    lastUsed: "2026-05-20T10:00:00Z",
    usageCount: 42,
    lastUpdatedBy: "Tech. Réseau",
  },
  {
    id: "s3",
    reference: "SERV-NET-CABLAGE-CAT6",
    name: "Câblage réseau Cat6",
    family: "Réseau",
    unit: "Point réseau",
    internalCost: 1800,
    sellingPrice: 3800,
    margin: 2000,
    marginRate: 111.11,
    status: "Actif",
    description:
      "Tirage de câble, raccordement plastron/baie et test de continuité.",
    estimatedDuration: "1.5 heures (moyenne par prise)",
    conditions: "Chemins de câbles préparés ou existants.",
    requiredSkills: ["Câblerie cuivre", "Outils de test réseau"],
    prerequisites: [
      "Plans des goulottes/chemins de câbles",
      "Matériel de tirage prêt",
    ],
    executionSteps: [
      "Repérage des longueurs",
      "Tirage du câble",
      "Raccordement côté baie (panneau de brassage)",
      "Raccordement côté utilisateur (prise/plastron)",
      "Étiquetage",
      "Test au certificateur",
    ],
    associatedEquipment: [
      "Bobine câble Cat6",
      "Prises RJ45",
      "Panneau de brassage",
      "Goulottes",
    ],
    requiredDocuments: ["Plan de câblage", "Fiche de test et certification"],
    qualityCheckpoints: [
      "Respect du rayon de courbure",
      "Conformité du schéma de câblage (EIA/TIA)",
      "Test de continuité OK",
      "Étiquettes lisibles et normées",
    ],
    createdAt: "2024-11-05T08:00:00Z",
    lastUsed: "2026-05-25T09:15:00Z",
    usageCount: 312,
    lastUpdatedBy: "Resp. Chantier",
  },
  {
    id: "s4",
    reference: "SERV-FIBRE-RACCORDEMENT",
    name: "Raccordement fibre optique",
    family: "Fibre optique",
    unit: "Intervention",
    internalCost: 8000,
    sellingPrice: 18000,
    margin: 10000,
    marginRate: 125,
    status: "Actif",
    description: "Soudure de pigtails, test réflectométrique et d'atténuation.",
    estimatedDuration: "1 jour par tiroir",
    conditions: "La fibre doit être tirée. Environnement propre.",
    requiredSkills: [
      "Soudure fibre",
      "Manipulations optiques",
      "Analyse réflectométrique",
    ],
    prerequisites: ["Fibre en attente à souder", "Tiroirs optiques posés"],
    executionSteps: [
      "Préparation de la fibre (dénudage, clivage)",
      "Réalisation des soudures (fusion)",
      "Rangement des cassettes",
      "Test photométrique sur chaque brin",
      "Test OTDR",
    ],
    associatedEquipment: [
      "Soudeuse fibre optique",
      "Cliveuse",
      "Tiroir optique",
      "Manchons de protection",
      "Réflectomètre optique",
    ],
    requiredDocuments: [
      "Cahier de recette optique",
      "Synoptique des liaisons optiques",
    ],
    qualityCheckpoints: [
      "Atténuation des soudures < 0.1dB",
      "Fibre non tendue",
      "Rangement propre en cassette",
    ],
    createdAt: "2025-06-20T08:00:00Z",
    lastUsed: "2026-05-15T15:00:00Z",
    usageCount: 18,
    lastUpdatedBy: "Admin. technique",
  },
  {
    id: "s5",
    reference: "SERV-NET-CONFIG-SWITCH",
    name: "Configuration switch manageable",
    family: "Réseau",
    unit: "Équipement configuré",
    internalCost: 4000,
    sellingPrice: 10000,
    margin: 6000,
    marginRate: 150,
    status: "Actif",
    description: "Configuration VLANs, QoS, STP, accès management distant.",
    estimatedDuration: "3 heures",
    conditions: "Cahier des charges réseau validé.",
    requiredSkills: [
      "Architecture réseau LAN",
      "Administration d'équipements L2/L3 (Cisco/Aruba/etc.)",
    ],
    prerequisites: [
      "Architecture logique validée",
      "Plage d'adresses de management fournie",
      "Tableau de brassage OK",
    ],
    executionSteps: [
      "Connexion console en local",
      "Application du hostname et du mot de passe admin",
      "Configuration des interfaces et des VLAN(s)",
      "Configuration des options de sécurité (DCHP snooping, port-security)",
      "Sauvegarde de la configuration (start-up config)",
    ],
    associatedEquipment: [
      "Switch réseau L2/L3",
      "Câble console",
      "Transceivers SFP",
    ],
    requiredDocuments: [
      "Matrice des VLANs et IPs",
      "Schéma logique d'interconnexion",
    ],
    qualityCheckpoints: [
      "Accès distant OK en SSH, pas en Telnet",
      "Les ports inutilisés sont shutdown",
      "Le RSTP/MSTP élit bien le root bridge",
    ],
    createdAt: "2025-03-12T14:00:00Z",
    lastUsed: "2026-05-22T10:45:00Z",
    usageCount: 65,
    lastUpdatedBy: "Tech. Réseau",
  },
  {
    id: "s6",
    reference: "SERV-SEC-CONTROLE-ACCES",
    name: "Paramétrage contrôle d'accès",
    family: "Contrôle d'accès",
    unit: "Forfait",
    internalCost: 6000,
    sellingPrice: 14000,
    margin: 8000,
    marginRate: 133.33,
    status: "Actif",
    description:
      "Programmation des lecteurs, badges, profils d'accès et horaires.",
    estimatedDuration: "1 jour",
    conditions:
      "Matériel installé (tourniquets/lecteurs) et connecté au réseau.",
    requiredSkills: [
      "Configuration logiciel de sûreté",
      "Administration bases de données légères",
    ],
    prerequisites: [
      "Liste du personnel à badger fournie",
      "Emploi du temps des groupes validé",
    ],
    executionSteps: [
      "Installation ou configuration du logiciel serveur",
      "Enrôlement des automates/contrôleurs de portes",
      "Définition des zones, plages horaires, et groupes",
      "Création des premiers utilisateurs/badges test",
      "Test des scénarios de rejet et validation d'ouverture",
    ],
    associatedEquipment: [
      "Lecteurs de badges",
      "Cartes MIFARE/DESFire",
      "Portes/Gâches, Tourniquets",
    ],
    requiredDocuments: [
      "Matrice des droits d'accès",
      "Livrable logiciel d'accès",
    ],
    qualityCheckpoints: [
      "Le refus d'accès sur horaires est effectif",
      "Ouverture pompier fonctionnelle (fail safe)",
    ],
    createdAt: "2025-04-18T09:00:00Z",
    lastUsed: "2026-05-18T13:30:00Z",
    usageCount: 22,
    lastUpdatedBy: "Resp. Chantier",
  },
  {
    id: "s7",
    reference: "SERV-MAINT-PREVENTIVE",
    name: "Maintenance préventive",
    family: "Maintenance",
    unit: "Intervention",
    internalCost: 7000,
    sellingPrice: 16000,
    margin: 9000,
    marginRate: 128.57,
    status: "Actif",
    description:
      "Visite programmée, dépoussiérage, contrôle logiciel, mise à jour, rapport.",
    estimatedDuration: "Demi-journée à une journée complète selon le site",
    conditions: "A planifier selon contrat SLA.",
    requiredSkills: [
      "Diagnostic terrain multi-techno",
      "Analyse log",
      "Sens du service client",
    ],
    prerequisites: [
      "Copie du contrat de maintenance",
      "Carnet d'entretien du site existant",
      "Prise de RDV confirmée avec le client",
    ],
    executionSteps: [
      "Vérification physique des baies et équipements (serrage, état LED, température)",
      "Tests de fonctionnement",
      "Sauvegarde des configurations",
      "Nettoyage et entretien basique (lentilles caméras, ventilation des NVR, etc.)",
      "Mises à jour mineures firmware",
      "Rédaction de la fiche d'intervention et signature du client",
    ],
    associatedEquipment: ["Kits de nettoyage, outillage standard", "Air sec"],
    requiredDocuments: [
      "Contrat maintenance",
      "Fiche check-list préventive de référence",
    ],
    qualityCheckpoints: [
      "Toutes les anomalies, même légères, sont remontées dans le rapport",
      "Espace client nettoyé après intervention",
    ],
    createdAt: "2024-01-22T08:00:00Z",
    lastUsed: "2026-05-28T09:30:00Z",
    usageCount: 210,
    lastUpdatedBy: "Admin. technique",
  },
  {
    id: "s8",
    reference: "SERV-SUPPORT-DISTANCE",
    name: "Support à distance",
    family: "Support",
    unit: "Heure",
    internalCost: 1500,
    sellingPrice: 4000,
    margin: 2500,
    marginRate: 166.67,
    status: "Actif",
    description:
      "Assistance téléphonique et prise en main à distance (TeamViewer/AnyDesk).",
    estimatedDuration: "1 heure",
    conditions: "Client disposant d'un accès internet fonctionnel.",
    requiredSkills: [
      "Diagnostic Helpdesk N1/N2",
      "Pédagogie et patience",
      "Outils de bureau à distance",
    ],
    prerequisites: [
      "Client identifié dans la base",
      "Ticketing de la panne bien renseigné",
      "Autorisation de prise en main à distance",
    ],
    executionSteps: [
      "Diagnostic par échange verbal",
      "Ouverture de connexion distante",
      "Isolation du défaut et dépannage logiciel (relais/VLAN, redémarrage logiciel, correction IP, etc.)",
      "Validation du correctif avec l'utilisateur au bout de la ligne",
      "Clôture du ticket et envoi mail de résolution",
    ],
    associatedEquipment: [
      "Station de support Helpdesk",
      "Logiciel prise en main à distance",
    ],
    requiredDocuments: ["Historique des tickets client"],
    qualityCheckpoints: [
      "Connexion chiffrée",
      "Solution notée dans le ticket pour la base de connaissances",
    ],
    createdAt: "2024-02-14T09:00:00Z",
    lastUsed: "2026-05-29T10:15:00Z",
    usageCount: 840,
    lastUpdatedBy: "Tech. Support",
  },
  {
    id: "s9",
    reference: "SERV-FORM-UTILISATEUR",
    name: "Formation utilisateur",
    family: "Formation",
    unit: "Jour",
    internalCost: 12000,
    sellingPrice: 28000,
    margin: 16000,
    marginRate: 133.33,
    status: "Actif",
    description:
      "Formation du personnel sur l'utilisation des systèmes (logiciels de supervision).",
    estimatedDuration: "1 jour",
    conditions:
      "Salle dédiée ou poste opérateur libre de contraintes pendant la formation.",
    requiredSkills: [
      "Animation de formation technique",
      "Connaissance experte de l'usage final",
    ],
    prerequisites: [
      "Supports de cours rédigés et validés",
      "Système cible totalement déployé et sans dysfonctionnement bloquant",
    ],
    executionSteps: [
      "Introduction aux concepts (CCTV, intrusion, accès)",
      "Manipulation des interfaces graphiques (login, changement MDP)",
      "Fonctions du quotidien (relecture vidéo, ajout badge, génération rapport)",
      "Procédure en cas de problème",
      "Remise de l'attestation de formation et du support de cours/vidéo",
    ],
    associatedEquipment: [
      "Vidéoprojecteur (ou salle client)",
      "Station de supervision, PC formateur",
    ],
    requiredDocuments: [
      "Support de cours PDF formateur",
      "Mémo stagiaire / Quick start guide",
      "Feuille d'émargement",
    ],
    qualityCheckpoints: [
      "Stagiaires autonomes sur les tâches basiques confirmées par exercice",
      "Évaluation de satisfaction réalisée",
    ],
    createdAt: "2025-07-02T10:00:00Z",
    lastUsed: "2026-05-12T09:00:00Z",
    usageCount: 34,
    lastUpdatedBy: "Formateur",
  },
  {
    id: "s10",
    reference: "SERV-CLOUD-MIGRATION",
    name: "Migration cloud",
    family: "Cloud",
    unit: "Jour",
    internalCost: 18000,
    sellingPrice: 45000,
    margin: 27000,
    marginRate: 150,
    status: "Actif",
    description:
      "Transfert d'infrastructures de données et applications vers service cloud (Azure, AWS, VSaaS).",
    estimatedDuration: "Modulable, de 2 à 10 jours selon complexité",
    conditions:
      "Débit internet suffisant sur site et accord de confidentialité actif.",
    requiredSkills: [
      "Architecture Cloud Publique/Privée",
      "Migration de bases de données",
      "Sécurité des Flux/VPN",
    ],
    prerequisites: [
      "Cartographie des systèmes à migrer validée",
      "Fenêtre de coupure/bascule validée par le client",
      "Comptes/tenant cloud provisionnés",
    ],
    executionSteps: [
      "Synchronisation initiale des données (sauvegarde / réplication de masse)",
      "Configuration de l'infra Cloud (réseau Virtuel, règles sécurité, sizing calcul/stockage)",
      "Déploiement applicatif",
      "Basculement DNS et des flux (Cut-over)",
      "Test intensif de post-migration (validation fonctionnelle)",
    ],
    associatedEquipment: ["Console Cloud", "VPN Site-à-Site"],
    requiredDocuments: [
      "Plan de migration",
      "Cahier de recette PRA/PCA migration",
    ],
    qualityCheckpoints: [
      "Aucune perte de données",
      "Downtime respecté",
      "Sécurité réseau Cloud auditée comme OK",
    ],
    createdAt: "2025-08-30T10:00:00Z",
    lastUsed: "2026-04-20T10:00:00Z",
    usageCount: 8,
    lastUpdatedBy: "Architecte Cloud",
  },
];
