import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    reference: "CAM-HIK-2CD2043",
    name: "Caméra IP Hikvision DS-2CD2043",
    family: "CCTV",
    brand: "Hikvision",
    model: "DS-2CD2043G2",
    mainSupplier: "DistriCam",
    purchasePrice: 120.0,
    sellingPrice: 180.0,
    margin: 60.0,
    marginRate: 33.33,
    physicalStock: 45,
    reservedStock: 5,
    availableStock: 40,
    orderedStock: 20,
    minThreshold: 10,
    supplierWarrantyMonths: 36,
    clientWarrantyMonths: 24,
    status: "Actif",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Caméra d'extérieur IP 4MP avec vision nocturne jusqu'à 30m.",
    type: "Équipement",
    createdAt: "2023-01-15",
    tags: ["PoE", "IP67", "4MP", "Cloud ready"],
    averagePurchasePrice: 115.5,
    lastPriceUpdate: "2025-11-20",
  },
  {
    id: "p2",
    reference: "NVR-HIK-16CH",
    name: "NVR Hikvision 16 canaux",
    family: "CCTV",
    brand: "Hikvision",
    model: "DS-7616NI-K2/16P",
    mainSupplier: "DistriCam",
    purchasePrice: 250.0,
    sellingPrice: 380.0,
    margin: 130.0,
    marginRate: 34.21,
    physicalStock: 8,
    reservedStock: 3,
    availableStock: 5,
    orderedStock: 0,
    minThreshold: 5,
    supplierWarrantyMonths: 36,
    clientWarrantyMonths: 24,
    status: "Sous seuil",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Enregistreur Vidéo Réseau 16 Canaux avec 16 ports PoE.",
    type: "Équipement",
    createdAt: "2023-02-10",
    tags: ["NVR", "16 ports", "PoE+", "Rackable"],
    averagePurchasePrice: 245.0,
    lastPriceUpdate: "2026-01-10",
  },
  {
    id: "p3",
    reference: "SW-TPL-24P",
    name: "Switch PoE 24 ports TP-Link",
    family: "Réseau",
    brand: "TP-Link",
    model: "T1500G-10MPS",
    mainSupplier: "NetDev",
    purchasePrice: 180.0,
    sellingPrice: 260.0,
    margin: 80.0,
    marginRate: 30.76,
    physicalStock: 0,
    reservedStock: 0,
    availableStock: 0,
    orderedStock: 15,
    minThreshold: 2,
    supplierWarrantyMonths: 60,
    clientWarrantyMonths: 24,
    status: "En rupture",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Switch Gigabit PoE+ 24 ports de niveau 2.",
    type: "Équipement",
    createdAt: "2023-03-20",
    tags: ["24 ports", "PoE+", "Rackable", "Gigabit"],
    averagePurchasePrice: 175.0,
    lastPriceUpdate: "2025-12-05",
  },
  {
    id: "p4",
    reference: "ROUT-MIK-4011",
    name: "Routeur MikroTik RB4011",
    family: "Réseau",
    brand: "MikroTik",
    model: "RB4011iGS+RM",
    mainSupplier: "NetDev",
    purchasePrice: 190.0,
    sellingPrice: 290.0,
    margin: 100.0,
    marginRate: 34.48,
    physicalStock: 12,
    reservedStock: 2,
    availableStock: 10,
    orderedStock: 0,
    minThreshold: 3,
    supplierWarrantyMonths: 12,
    clientWarrantyMonths: 12,
    status: "Actif",
    requiresSerialNumber: true,
    isStockable: true,
    description:
      "Routeur Ethernet Gigabit 10 ports avec accélération matérielle IPsec.",
    type: "Équipement",
    createdAt: "2023-04-05",
    tags: ["Gigabit", "IPsec", "Rackable", "10 ports"],
    averagePurchasePrice: 185.0,
    lastPriceUpdate: "2025-10-12",
  },
  {
    id: "p5",
    reference: "OND-APC-1500",
    name: "Onduleur APC 1500VA",
    family: "Onduleurs",
    brand: "APC",
    model: "BR1500G-FR",
    mainSupplier: "PowerSupply",
    purchasePrice: 210.0,
    sellingPrice: 320.0,
    margin: 110.0,
    marginRate: 34.37,
    physicalStock: 15,
    reservedStock: 5,
    availableStock: 10,
    orderedStock: 10,
    minThreshold: 5,
    supplierWarrantyMonths: 24,
    clientWarrantyMonths: 24,
    status: "Actif",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Onduleur Pro avec LCD (1500 Volts/Amps).",
    type: "Équipement",
    createdAt: "2023-05-12",
    tags: ["1500VA", "LCD", "Line-interactive"],
    averagePurchasePrice: 205.0,
    lastPriceUpdate: "2025-08-30",
  },
  {
    id: "p6",
    reference: "CBL-CAT6-UTP",
    name: "Câble réseau Cat6 UTP 305m",
    family: "Consommables",
    brand: "Generic",
    model: "Cat6-UTP-LSZH",
    mainSupplier: "CablingPro",
    purchasePrice: 45.0,
    sellingPrice: 85.0,
    margin: 40.0,
    marginRate: 47.05,
    physicalStock: 30,
    reservedStock: 10,
    availableStock: 20,
    orderedStock: 50,
    minThreshold: 15,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: true,
    description: "Bobine de 305m de câble réseau Catégorie 6 UTP.",
    type: "Consommable",
    createdAt: "2023-06-01",
    tags: ["Cat6", "UTP", "305m", "LSZH"],
    averagePurchasePrice: 42.0,
    lastPriceUpdate: "2026-02-01",
  },
  {
    id: "p7",
    reference: "RACK-12U",
    name: "Baie réseau 12U",
    family: "Réseau",
    brand: "Generic",
    model: "Rack-12U-600x450",
    mainSupplier: "CablingPro",
    purchasePrice: 90.0,
    sellingPrice: 150.0,
    margin: 60.0,
    marginRate: 40.0,
    physicalStock: 3,
    reservedStock: 3,
    availableStock: 0,
    orderedStock: 0,
    minThreshold: 1,
    supplierWarrantyMonths: 12,
    clientWarrantyMonths: 12,
    status: "En rupture",
    requiresSerialNumber: false,
    isStockable: true,
    description: "Coffret mural 12U profondeur 450mm.",
    type: "Équipement",
    createdAt: "2023-07-22",
    tags: ["12U", "Mural", "450mm"],
    averagePurchasePrice: 85.0,
    lastPriceUpdate: "2025-09-15",
  },
  {
    id: "p8",
    reference: "CTRL-ZKT",
    name: "Contrôleur d'accès ZKTeco",
    family: "Contrôle d'accès",
    brand: "ZKTeco",
    model: "InBio260",
    mainSupplier: "SecurityDist",
    purchasePrice: 150.0,
    sellingPrice: 250.0,
    margin: 100.0,
    marginRate: 40.0,
    physicalStock: 2,
    reservedStock: 0,
    availableStock: 2,
    orderedStock: 0,
    minThreshold: 2,
    supplierWarrantyMonths: 24,
    clientWarrantyMonths: 12,
    status: "Sous seuil",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Contrôleur 2 portes multi-biométrique.",
    type: "Équipement",
    createdAt: "2023-08-30",
    tags: ["Biométrique", "2 portes", "IP"],
    averagePurchasePrice: 145.0,
    lastPriceUpdate: "2026-01-20",
  },
  {
    id: "p9",
    reference: "SRV-DELL-R440",
    name: "Serveur Dell PowerEdge R440",
    family: "Serveurs",
    brand: "Dell",
    model: "PowerEdge R440",
    mainSupplier: "DellDirect",
    purchasePrice: 1200.0,
    sellingPrice: 1800.0,
    margin: 600.0,
    marginRate: 33.33,
    physicalStock: 1,
    reservedStock: 1,
    availableStock: 0,
    orderedStock: 2,
    minThreshold: 1,
    supplierWarrantyMonths: 36,
    clientWarrantyMonths: 36,
    status: "Sous seuil",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Serveur rack 1U, Intel Xeon Silver, 32GB RAM, 2x 480GB SSD.",
    type: "Équipement",
    createdAt: "2024-01-15",
    tags: ["Rack 1U", "Xeon", "SSD", "ProSupport"],
    averagePurchasePrice: 1200.0,
    lastPriceUpdate: "2025-11-20",
  },
  {
    id: "p10",
    reference: "NAS-SYN-920",
    name: "NAS Synology DS920+",
    family: "Serveurs",
    brand: "Synology",
    model: "DS920+",
    mainSupplier: "DistriCloud",
    purchasePrice: 450.0,
    sellingPrice: 650.0,
    margin: 200.0,
    marginRate: 30.76,
    physicalStock: 4,
    reservedStock: 1,
    availableStock: 3,
    orderedStock: 0,
    minThreshold: 2,
    supplierWarrantyMonths: 36,
    clientWarrantyMonths: 36,
    status: "Actif",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Serveur NAS 4 baies, évolutif, idéal petites entreprises.",
    type: "Équipement",
    createdAt: "2024-02-10",
    tags: ["NAS", "4 baies", "Sauvegarde"],
    averagePurchasePrice: 440.0,
    lastPriceUpdate: "2025-10-10",
  },
  {
    id: "p11",
    reference: "CON-RJ45-B100",
    name: "Boîte de 100 connecteurs RJ45",
    family: "Consommables",
    brand: "Generic",
    model: "RJ45-Cat6-Shielded",
    mainSupplier: "CablingPro",
    purchasePrice: 15.0,
    sellingPrice: 35.0,
    margin: 20.0,
    marginRate: 57.14,
    physicalStock: 120,
    reservedStock: 20,
    availableStock: 100,
    orderedStock: 0,
    minThreshold: 30,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: true,
    description: "Connecteurs RJ45 blindés Catégorie 6.",
    type: "Consommable",
    createdAt: "2023-01-20",
    tags: ["Connecteurs", "RJ45", "Cat6"],
    averagePurchasePrice: 14.5,
    lastPriceUpdate: "2025-05-15",
  },
  {
    id: "p12",
    reference: "FIB-JAR-LC-3M",
    name: "Jarretière optique LC-LC 3m",
    family: "Fibre optique",
    brand: "Generic",
    model: "OM3-LC-LC-3M",
    mainSupplier: "FiberDist",
    purchasePrice: 8.0,
    sellingPrice: 18.0,
    margin: 10.0,
    marginRate: 55.55,
    physicalStock: 50,
    reservedStock: 5,
    availableStock: 45,
    orderedStock: 0,
    minThreshold: 20,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: true,
    description: "Cordon optique multimode OM3 LC/PC-LC/PC longueur 3 mètres.",
    type: "Consommable",
    createdAt: "2023-04-10",
    tags: ["Fibre", "LC", "OM3", "3m"],
    averagePurchasePrice: 7.5,
    lastPriceUpdate: "2025-06-12",
  },
  {
    id: "p13",
    reference: "RFID-CARD-100",
    name: "Lot de 100 Badges RFID",
    family: "Consommables",
    brand: "ZKTeco",
    model: "Mifare 13.56MHz",
    mainSupplier: "SecurityDist",
    purchasePrice: 25.0,
    sellingPrice: 60.0,
    margin: 35.0,
    marginRate: 58.33,
    physicalStock: 15,
    reservedStock: 2,
    availableStock: 13,
    orderedStock: 20,
    minThreshold: 10,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: true,
    description: "Cartes RFID Mifare standard pour contrôle d'accès.",
    type: "Consommable",
    createdAt: "2023-08-01",
    tags: ["Badge", "RFID", "Mifare"],
    averagePurchasePrice: 24.0,
    lastPriceUpdate: "2025-07-01",
  },
  {
    id: "p14",
    reference: "LIC-MILE-ESS",
    name: "Licence Camera VMS",
    family: "Cloud / licences",
    brand: "Milestone",
    model: "XProtect Essential+",
    mainSupplier: "SoftwareDist",
    purchasePrice: 40.0,
    sellingPrice: 80.0,
    margin: 40.0,
    marginRate: 50.0,
    physicalStock: 0,
    reservedStock: 0,
    availableStock: 0,
    orderedStock: 0,
    minThreshold: 0,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: false,
    description: "Licence par caméra pour logiciel VMS Milestone.",
    type: "Licence",
    createdAt: "2024-05-15",
    tags: ["VMS", "Licence", "Logiciel"],
  },
  {
    id: "p15",
    reference: "LIC-ESET-1Y",
    name: "Antivirus Entreprise 1 an",
    family: "Cloud / licences",
    brand: "ESET",
    model: "Endpoint Security",
    mainSupplier: "SoftwareDist",
    purchasePrice: 25.0,
    sellingPrice: 50.0,
    margin: 25.0,
    marginRate: 50.0,
    physicalStock: 0,
    reservedStock: 0,
    availableStock: 0,
    orderedStock: 0,
    minThreshold: 0,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Actif",
    requiresSerialNumber: false,
    isStockable: false,
    description: "Licence antivirus ESET pour poste de travail, validité 1 an.",
    type: "Licence",
    createdAt: "2024-06-01",
    tags: ["Securité", "Antivirus", "Annuel"],
  },
  {
    id: "p16",
    reference: "CAM-OLD-720P",
    name: "Caméra dôme 720p",
    family: "CCTV",
    brand: "Generic",
    model: "Dome-720",
    mainSupplier: "DistriCam",
    purchasePrice: 30.0,
    sellingPrice: 45.0,
    margin: 15.0,
    marginRate: 33.33,
    physicalStock: 2,
    reservedStock: 0,
    availableStock: 2,
    orderedStock: 0,
    minThreshold: 0,
    supplierWarrantyMonths: 12,
    clientWarrantyMonths: 12,
    status: "Obsolète",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Ancien modèle de caméra 720p analogique.",
    type: "Équipement",
    createdAt: "2020-01-10",
    tags: ["Analogique", "720p"],
  },
  {
    id: "p17",
    reference: "ROUT-OBS-2015",
    name: "Routeur ADSL",
    family: "Réseau",
    brand: "Linksys",
    model: "WRT54G",
    mainSupplier: "NetDev",
    purchasePrice: 20.0,
    sellingPrice: 30.0,
    margin: 10.0,
    marginRate: 33.33,
    physicalStock: 0,
    reservedStock: 0,
    availableStock: 0,
    orderedStock: 0,
    minThreshold: 0,
    supplierWarrantyMonths: 0,
    clientWarrantyMonths: 0,
    status: "Désactivé",
    requiresSerialNumber: true,
    isStockable: true,
    description: "Modèle ancien. Ne plus vendre.",
    type: "Équipement",
    createdAt: "2015-05-12",
    tags: ["ADSL", "Obsolète"],
  },
];
