import { StockItem } from "./types";

export const mockStockData: StockItem[] = [
  {
    id: "p-001",
    reference: "HIK-CAM-001",
    name: "Caméra Dôme IP 4MP Hikvision",
    family: "Vidéosurveillance",
    physicalStock: 45,
    reservedStock: 5,
    availableStock: 40,
    orderedStock: 20,
    minStockThreshold: 10,
    mainLocation: "Dépôt Principal - Allée A",
    status: "en_stock",
    locations: [
      { id: "loc-1", name: "Dépôt principal", quantity: 39, type: "depot" },
      {
        id: "loc-2",
        name: "Véhicule Technicien A",
        quantity: 2,
        type: "vehicule",
      },
      { id: "loc-3", name: "Chantier Hôtel X", quantity: 4, type: "chantier" },
    ],
    movements: [
      {
        id: "m-1",
        date: "2023-11-20T10:30:00Z",
        type: "entree",
        quantity: 10,
        user: "Jean Dupont",
        document: "BL-2023-1002",
        comment: "Réception fournisseur",
      },
      {
        id: "m-2",
        date: "2023-11-18T14:15:00Z",
        type: "sortie",
        quantity: -4,
        user: "Marc Tech",
        document: "INT-2023-088",
        comment: "Installation chantier Hôtel X",
      },
      {
        id: "m-3",
        date: "2023-10-15T09:00:00Z",
        type: "correction",
        quantity: 1,
        user: "Luc Inventaire",
        comment: "Inventaire annuel",
      },
    ],
    reservations: [
      {
        id: "r-1",
        project: "Chantier Hôtel X",
        quantity: 4,
        date: "2023-11-10T11:00:00Z",
        status: "active",
        responsible: "Marc Tech",
      },
      {
        id: "r-2",
        project: "Devis Mairie",
        quantity: 1,
        date: "2023-11-25T16:20:00Z",
        status: "active",
        responsible: "Alice Com",
      },
    ],
    isSerialized: true,
    serialNumbers: [
      {
        serial: "SN-HIK-00101",
        status: "en_stock",
        location: "Dépôt principal",
      },
      {
        serial: "SN-HIK-00102",
        status: "en_stock",
        location: "Dépôt principal",
      },
      {
        serial: "SN-HIK-00103",
        status: "installe",
        location: "Chantier Hôtel X",
      },
    ],
  },
  {
    id: "p-002",
    reference: "CISCO-SW-24P",
    name: "Switch Cisco 24 ports PoE+",
    family: "Réseau",
    physicalStock: 2,
    reservedStock: 2,
    availableStock: 0,
    orderedStock: 5,
    minStockThreshold: 3,
    mainLocation: "Dépôt Principal - Allée B",
    status: "rupture",
    locations: [
      { id: "loc-4", name: "Dépôt principal", quantity: 2, type: "depot" },
    ],
    movements: [
      {
        id: "m-4",
        date: "2023-11-05T08:30:00Z",
        type: "sortie",
        quantity: -1,
        user: "Marc Tech",
        document: "INT-2023-085",
        comment: "Dépannage Site Y",
      },
    ],
    reservations: [
      {
        id: "r-3",
        project: "Renouvellement Infra Z",
        quantity: 2,
        date: "2023-11-20T14:00:00Z",
        status: "active",
        responsible: "Jean Dupont",
      },
    ],
    isSerialized: true,
  },
  {
    id: "p-003",
    reference: "APC-UPS-1500",
    name: "Onduleur APC Smart-UPS 1500VA",
    family: "Énergie",
    physicalStock: 8,
    reservedStock: 0,
    availableStock: 8,
    orderedStock: 0,
    minStockThreshold: 10,
    mainLocation: "Dépôt Principal - Allée C",
    status: "sous_seuil",
    locations: [
      { id: "loc-5", name: "Dépôt principal", quantity: 8, type: "depot" },
    ],
    movements: [
      {
        id: "m-5",
        date: "2023-09-12T10:00:00Z",
        type: "entree",
        quantity: 15,
        user: "Luc Inventaire",
        document: "BL-2023-0912",
        comment: "Commande stock",
      },
    ],
    reservations: [],
    isSerialized: true,
  },
  {
    id: "p-004",
    reference: "CBL-RJ45-CAT6",
    name: "Bobine Câble RJ45 Cat6 305m",
    family: "Câblage",
    physicalStock: 12,
    reservedStock: 0,
    availableStock: 12,
    orderedStock: 10,
    minStockThreshold: 5,
    mainLocation: "Dépôt Principal - Rack Câbles",
    status: "en_stock",
    locations: [
      { id: "loc-6", name: "Dépôt principal", quantity: 10, type: "depot" },
      {
        id: "loc-7",
        name: "Véhicule Technicien B",
        quantity: 2,
        type: "vehicule",
      },
    ],
    movements: [
      {
        id: "m-6",
        date: "2023-12-01T08:00:00Z",
        type: "transfert",
        quantity: 2,
        user: "Luc Inventaire",
        comment: "Transfert dépôt vers Véhicule Technicien B",
      },
    ],
    reservations: [],
    isSerialized: false,
  },
  {
    id: "p-005",
    reference: "ZKT-CTRL-INBIO260",
    name: "Contrôleur ZKTeco InBio260",
    family: "Contrôle d'accès",
    physicalStock: 0,
    reservedStock: 0,
    availableStock: 0,
    orderedStock: 5,
    minStockThreshold: 2,
    mainLocation: "Dépôt Principal - Allée E",
    status: "rupture",
    locations: [],
    movements: [
      {
        id: "m-7",
        date: "2023-11-28T16:00:00Z",
        type: "sortie",
        quantity: -2,
        user: "Admin",
        document: "INT-2023-090",
        comment: "Sortie chantier Siège Social",
      },
    ],
    reservations: [],
    isSerialized: true,
  },
  {
    id: "p-006",
    reference: "DELL-R440-SVR",
    name: "Serveur Dell PowerEdge R440",
    family: "Serveurs",
    physicalStock: 3,
    reservedStock: 1,
    availableStock: 2,
    orderedStock: 0,
    minStockThreshold: 1,
    mainLocation: "Dépôt Principal - Salle Sécurisée",
    status: "en_stock",
    locations: [
      { id: "loc-8", name: "Dépôt principal", quantity: 2, type: "depot" },
      {
        id: "loc-9",
        name: "Atelier Intégration",
        quantity: 1,
        type: "chantier",
      }, // Currently being prepared
    ],
    movements: [
      {
        id: "m-8",
        date: "2023-11-29T09:30:00Z",
        type: "transfert",
        quantity: 1,
        user: "Tech Prépa",
        comment: "Transfert pour pré-configuration en atelier",
      },
    ],
    reservations: [
      {
        id: "r-4",
        project: "Déploiement Serveur Client ABC",
        quantity: 1,
        date: "2023-11-29T09:00:00Z",
        status: "active",
        responsible: "Tech Prépa",
      },
    ],
    isSerialized: true,
    serialNumbers: [
      {
        serial: "DELL-SVS-001",
        status: "en_stock",
        location: "Dépôt principal",
      },
      {
        serial: "DELL-SVS-002",
        status: "en_stock",
        location: "Dépôt principal",
      },
      {
        serial: "DELL-SVS-003",
        status: "installe",
        location: "Atelier Intégration",
      }, // simulating state
    ],
  },
  {
    id: "p-007",
    reference: "HIK-NVR-16CH",
    name: "NVR Hikvision 16 Canaux",
    family: "Vidéosurveillance",
    physicalStock: 1,
    reservedStock: 1,
    availableStock: 0,
    orderedStock: 2,
    minStockThreshold: 2,
    mainLocation: "Dépôt Principal - Allée A",
    status: "sous_seuil",
    locations: [
      { id: "loc-10", name: "Zone SAV", quantity: 1, type: "retour" }, // In SAV
    ],
    movements: [
      {
        id: "m-9",
        date: "2023-11-25T14:20:00Z",
        type: "retour",
        quantity: 1,
        user: "SAV Tech",
        document: "SAV-2023-042",
        comment: "Retour client suite à panne, attente analyse",
      },
    ],
    reservations: [
      {
        id: "r-5",
        project: "Remplacement SAV Client DEF",
        quantity: 1,
        date: "2023-11-26T10:00:00Z",
        status: "active",
        responsible: "SAV Tech",
      },
    ],
    isSerialized: true,
  },
  {
    id: "p-008",
    reference: "MIK-RB4011",
    name: "Routeur MikroTik RB4011",
    family: "Réseau",
    physicalStock: 5,
    reservedStock: 0,
    availableStock: 5,
    orderedStock: 10,
    minStockThreshold: 5,
    mainLocation: "Dépôt Principal - Allée B",
    status: "en_stock",
    locations: [
      { id: "loc-11", name: "Dépôt principal", quantity: 5, type: "depot" },
    ],
    movements: [],
    reservations: [],
    isSerialized: true,
  },
  {
    id: "p-009",
    reference: "RJ45-PLUG-100",
    name: "Boîte 100 connecteurs RJ45",
    family: "Câblage",
    physicalStock: 15,
    reservedStock: 0,
    availableStock: 15,
    orderedStock: 0,
    minStockThreshold: 10,
    mainLocation: "Dépôt Principal - Allée C",
    status: "en_stock",
    locations: [
      { id: "loc-12", name: "Dépôt principal", quantity: 10, type: "depot" },
      {
        id: "loc-13",
        name: "Véhicule Technicien A",
        quantity: 2,
        type: "vehicule",
      },
      {
        id: "loc-14",
        name: "Véhicule Technicien B",
        quantity: 3,
        type: "vehicule",
      },
    ],
    movements: [
      {
        id: "m-10",
        date: "2023-11-30T07:45:00Z",
        type: "transfert",
        quantity: 5,
        user: "Magasinier",
        comment: "Réassort véhicules techs",
      },
    ],
    reservations: [],
    isSerialized: false,
  },
  {
    id: "p-010",
    reference: "FIB-SPLICE-TUB",
    name: "Protection d'épissure (100 u.)",
    family: "Fibre optique",
    physicalStock: 2,
    reservedStock: 0,
    availableStock: 2,
    orderedStock: 5,
    minStockThreshold: 5,
    mainLocation: "Dépôt Principal - Allée C",
    status: "sous_seuil",
    locations: [
      { id: "loc-15", name: "Dépôt principal", quantity: 2, type: "depot" },
    ],
    movements: [
      {
        id: "m-11",
        date: "2023-11-22T13:00:00Z",
        type: "sortie",
        quantity: -3,
        user: "Tech Fibre",
        document: "INT-2023-102",
        comment: "Raccordement FO ZI Sud",
      },
    ],
    reservations: [],
    isSerialized: false,
  },
];
