import { Client } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Hôtel El Aurassi',
    type: 'Hôtel',
    status: 'Actif',
    sector: 'Hôtellerie',
    mainContact: 'Amine Rahmouni',
    phone: '021 74 82 52',
    email: 'contact@el-aurassi.dz',
    sitesCount: 2,
    activeProjects: 1,
    installedEquipments: 45,
    address: '2 Boulevard Frantz Fanon',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: false,
    createdAt: '2024-01-15',
    reference: 'CLT-24-0001',
    sites: [
      { id: '1', name: 'Site Principal (Alger)', address: '2 Boulevard Frantz Fanon', city: 'Alger', type: 'Hôtel', installedEquipments: 35 },
      { id: '2', name: 'Annexe (Oran)', address: 'Front de mer', city: 'Oran', type: 'Hôtel', installedEquipments: 10 }
    ],
    projects: [
      { id: '1', reference: 'PRJ-24-012', name: 'Modernisation Vidéosurveillance', status: 'En cours', expectedDate: '2024-07-20' },
      { id: '2', reference: 'PRJ-24-045', name: 'Maintenance Réseau', status: 'Terminé', expectedDate: '2024-05-15' }
    ],
    history: [
      { id: '1', type: 'creation', date: '2024-01-15', title: 'Création de la fiche client', user: 'Admin' },
      { id: '2', type: 'project', date: '2024-02-10', title: 'Nouveau projet: Modernisation Vidéosurveillance', user: 'Manager' },
      { id: '3', type: 'installation', date: '2024-03-05', title: 'Installation de 12 caméras IP', user: 'Technicien' }
    ]
  },
  {
    id: '2',
    name: 'Clinique El Yasmine',
    type: 'Administration',
    status: 'Actif',
    sector: 'Santé',
    mainContact: 'Dr. Meriem Benali',
    phone: '023 45 67 89',
    email: 'info@elyasmine.dz',
    sitesCount: 1,
    activeProjects: 0,
    installedEquipments: 120,
    address: 'Rue des jardins, Birkhadem',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: true,
    createdAt: '2023-11-20'
  },
  {
    id: '3',
    name: 'Université UMMTO',
    type: 'École',
    status: 'Actif',
    sector: 'Éducation',
    mainContact: 'Prof. Karim Haddad',
    phone: '026 21 34 56',
    email: 'direction@ummto.dz',
    sitesCount: 4,
    activeProjects: 3,
    installedEquipments: 350,
    address: 'Hasnaoua, Tizi-Ouzou',
    city: 'Tizi-Ouzou',
    region: 'Kabylie',
    hasExpiredWarranties: false,
    createdAt: '2024-02-10'
  },
  {
    id: '4',
    name: 'SARL TechnoBuild',
    type: 'Entreprise',
    status: 'Actif',
    sector: 'Industrie',
    mainContact: 'Yacine Mansouri',
    phone: '031 92 14 78',
    email: 'y.mansouri@technobuild.com',
    sitesCount: 3,
    activeProjects: 2,
    installedEquipments: 25,
    address: 'Zone Industrielle, Oued Smar',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: false,
    createdAt: '2024-03-05'
  },
  {
    id: '5',
    name: 'Groupe AgroNord',
    type: 'Entreprise',
    status: 'Actif',
    sector: 'Industrie',
    mainContact: 'Omar Daoud',
    phone: '034 56 12 34',
    email: 'o.daoud@agronord.dz',
    sitesCount: 2,
    activeProjects: 0,
    installedEquipments: 68,
    address: 'Nationale 12, Freha',
    city: 'Béjaïa',
    region: 'Est',
    hasExpiredWarranties: false,
    createdAt: '2024-01-22'
  },
  {
    id: '6',
    name: 'École privée Les Oliviers',
    type: 'École',
    status: 'Actif',
    sector: 'Éducation',
    mainContact: 'Mme. Sarah Touati',
    phone: '021 33 44 55',
    email: 'admin@lesoliviers.edu.dz',
    sitesCount: 1,
    activeProjects: 1,
    installedEquipments: 12,
    address: 'Lotissement El Bina, Dely Brahim',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: false,
    createdAt: '2024-04-12'
  },
  {
    id: '7',
    name: 'Résidence Les Pins',
    type: 'Particulier',
    status: 'Actif',
    sector: 'Autre',
    mainContact: 'Syndic El Amine',
    phone: '023 88 99 00',
    email: 'syndic@lespins.dz',
    sitesCount: 1,
    activeProjects: 0,
    installedEquipments: 8,
    address: 'Staoueli, Alger Plage',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: false,
    createdAt: '2024-05-02'
  },
  {
    id: '8',
    name: 'Administration Wilaya',
    type: 'Administration',
    status: 'Archivé',
    sector: 'Services',
    mainContact: 'Secrétariat Général',
    phone: '027 12 34 56',
    email: 'wilaya@alger.gov.dz',
    sitesCount: 1,
    activeProjects: 0,
    installedEquipments: 42,
    address: 'Place du 1er Mai',
    city: 'Alger',
    region: 'Centre',
    hasExpiredWarranties: true,
    createdAt: '2022-10-15'
  }
];
