import { Fournisseur } from './types';

export const MOCK_FOURNISSEURS: Fournisseur[] = [
  {
    id: 'f-1',
    name: 'Hikvision Algérie',
    type: 'Distributeur',
    contactPrincipale: 'Amine Benali',
    telephone: '+213 550 12 34 56',
    email: 'contact@hikvision.dz',
    produitsAssocies: 145,
    derniereLivraison: '2026-05-28',
    statut: 'actif',
    tauxConformite: 98,
    commandesAttente: 3,
    pays: 'Algérie',
    delaiMoyenLivraison: '3 jours',
    modePaiement: 'Virement bancaire (45 jours)',
    reference: 'FRN-HIK-001',
    receptions: [
      {
        id: 'rec-1',
        fournisseurId: 'f-1',
        date: '2026-05-28T10:30:00Z',
        referenceBL: 'BL-HIK-2026-0042',
        referenceCommande: 'CMD-2026-089',
        nbProduits: 5,
        quantiteTotale: 150,
        valeurTotale: 450000,
        statut: 'validee',
        depot: 'Dépôt Principal',
        responsable: 'Admin',
        documents: [{ id: 'doc-1', name: 'BL-HIK-2026-0042.pdf', type: 'PDF', size: '250 KB' }]
      }
    ]
  },
  {
    id: 'f-2',
    name: 'Dahua Technology',
    type: 'Fabricant',
    contactPrincipale: 'Sarah Lami',
    telephone: '+213 770 98 76 54',
    email: 'sarah.l@dahua.dz',
    produitsAssocies: 89,
    derniereLivraison: '2026-06-01',
    statut: 'actif',
    tauxConformite: 95,
    commandesAttente: 1,
    pays: 'Chine / Algérie',
    delaiMoyenLivraison: '5 jours',
    modePaiement: 'Chèque à réception',
    reference: 'FRN-DAH-002',
    receptions: [
      {
        id: 'rec-2',
        fournisseurId: 'f-2',
        date: '2026-06-01T14:15:00Z',
        referenceBL: 'BL-DAH-08889',
        nbProduits: 2,
        quantiteTotale: 50,
        valeurTotale: 120000,
        statut: 'ecart',
        depot: 'Dépôt Secondaire',
        responsable: 'Admin'
      }
    ]
  },
  {
    id: 'f-3',
    name: 'TP-Link Distributor',
    type: 'Grossiste',
    contactPrincipale: 'Karim Ziani',
    telephone: '+213 555 11 22 33',
    email: 'sales@tplink-dist.com',
    produitsAssocies: 42,
    derniereLivraison: '2026-02-15',
    statut: 'inactif',
    tauxConformite: 82,
    commandesAttente: 0,
    pays: 'Algérie',
    delaiMoyenLivraison: '7 jours',
    modePaiement: 'Paiement comptant',
    reference: 'FRN-TPL-003'
  },
  {
    id: 'f-4',
    name: 'MikroTik Partner',
    type: 'Revendeur',
    contactPrincipale: 'Yassine M.',
    telephone: '+213 661 44 55 66',
    email: 'yassine@mikrotik.dz',
    produitsAssocies: 15,
    derniereLivraison: '2026-05-10',
    statut: 'actif',
    tauxConformite: 100,
    commandesAttente: 2,
    pays: 'Algérie',
    delaiMoyenLivraison: '2 jours',
    modePaiement: 'Virement bancaire (30 jours)',
    reference: 'FRN-MIK-004'
  },
  {
    id: 'f-5',
    name: 'APC Schneider',
    type: 'Fabricant',
    contactPrincipale: 'Nadia S.',
    telephone: '+33 1 23 45 67 89',
    email: 'contact@apc.fr',
    produitsAssocies: 34,
    derniereLivraison: '2026-01-20',
    statut: 'archive',
    tauxConformite: 99,
    commandesAttente: 0,
    pays: 'France',
    delaiMoyenLivraison: '15 jours',
    modePaiement: 'LC',
    reference: 'FRN-APC-005'
  },
  {
    id: 'f-6',
    name: 'Dell Technologies',
    type: 'Distributeur',
    contactPrincipale: 'Mourad Dell',
    telephone: '+213 550 99 88 77',
    email: 'commercial@dell.dz',
    produitsAssocies: 67,
    derniereLivraison: '2026-06-02',
    statut: 'actif',
    tauxConformite: 96,
    commandesAttente: 12,
    pays: 'Algérie',
    delaiMoyenLivraison: '4 jours',
    modePaiement: 'Virement (60 jours)',
    reference: 'FRN-DEL-006'
  },
  {
    id: 'f-7',
    name: 'ZKTeco Algérie',
    type: 'Filiale',
    contactPrincipale: 'Sofiane Z.',
    telephone: '+213 540 12 34 56',
    email: 'info@zkteco.dz',
    produitsAssocies: 28,
    derniereLivraison: '2026-05-25',
    statut: 'actif',
    tauxConformite: 75, // Faible
    commandesAttente: 5,
    pays: 'Algérie',
    delaiMoyenLivraison: '10 jours',
    modePaiement: 'Chèque',
    reference: 'FRN-ZKT-007'
  }
];
