import { InstalledEquipment } from "./types";

const now = new Date();

export const mockInstalledEquipments: InstalledEquipment[] = [
  {
    id: "eq-1",
    clientId: "c-hotel-x",
    clientName: "Hôtel X",
    siteId: "s-parking",
    siteName: "Parking",
    address: "15 Rue de l'Hôtellerie, 75015 Paris",
    zone: "Extérieur",
    productId: "p-001",
    productName: "Caméra IP Hikvision",
    productReference: "CAM-HIK-EXT",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-2CD2043G0-I",
    serialNumber: "HIK-10001",
    exactLocation: "Entrée principale",
    status: "actif",
    installationDate: "2023-05-10T10:00:00Z",
    supplierWarranty: 36,
    clientWarranty: 36,
    startOfWarranty: "2023-05-10T10:00:00Z",
    endOfWarranty: "2026-05-10T10:00:00Z",
    warrantyConditions: "Pièces et main d'œuvre",
    technician: "Marc Dubois",
    supplier: "DistriCam",
    purchaseDate: "2023-04-15T10:00:00Z",
    history: [
      {
        id: "h-1-1",
        date: "2023-05-10T10:00:00Z",
        type: "installation",
        description: "Installation et réglage angle",
        user: "Marc Dubois",
      },
    ],
    documents: [
      {
        id: "d-1-1",
        name: "PV_Recette.pdf",
        type: "pdf",
        url: "#",
        date: "2023-05-11T10:00:00Z",
      },
    ],
    interventions: [],
  },
  {
    id: "eq-2",
    clientId: "c-hotel-x",
    clientName: "Hôtel X",
    siteId: "s-parking",
    siteName: "Parking",
    address: "15 Rue de l'Hôtellerie, 75015 Paris",
    zone: "Extérieur",
    productId: "p-001",
    productName: "Caméra IP Hikvision",
    productReference: "CAM-HIK-EXT",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-2CD2043G0-I",
    serialNumber: "HIK-10002",
    exactLocation: "Parking nord",
    status: "en_panne",
    installationDate: "2023-06-01T10:00:00Z",
    supplierWarranty: 36,
    clientWarranty: 36,
    startOfWarranty: "2023-06-01T10:00:00Z",
    endOfWarranty: new Date(
      now.getFullYear(),
      now.getMonth() + 1,
      now.getDate(),
    ).toISOString(),
    warrantyConditions: "Pièces et main d'œuvre",
    technician: "Marc Dubois",
    supplier: "DistriCam",
    purchaseDate: "2023-04-15T10:00:00Z",
    history: [
      {
        id: "h-2-1",
        date: "2023-06-01T10:00:00Z",
        type: "installation",
        description: "Installation caméra parking",
        user: "Marc Dubois",
      },
      {
        id: "h-2-2",
        date: "2024-05-10T09:00:00Z",
        type: "panne",
        description: "Image noire signalée par client",
        user: "Support N1",
      },
    ],
    documents: [],
    interventions: [
      {
        id: "int-2-1",
        date: "2024-05-11T14:30:00Z",
        technician: "Luc Tech",
        type: "panne",
        diagnostic: "Connecteur RJ45 oxydé / câble endommagé",
        result: "En attente de devis pour retirer câble",
      },
    ],
  },
  {
    id: "eq-3",
    clientId: "c-hotel-x",
    clientName: "Hôtel X",
    siteId: "s-technique",
    siteName: "Salle technique",
    address: "15 Rue de l'Hôtellerie, 75015 Paris",
    zone: "Sous-sol",
    productId: "p-002",
    productName: "NVR Hikvision 16 canaux",
    productReference: "NVR-HIK-16",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-7616NI-K2/16P",
    serialNumber: "HIK-NVR-900",
    exactLocation: "Rack vidéo",
    status: "actif",
    installationDate: "2023-05-15T10:00:00Z",
    supplierWarranty: 36,
    clientWarranty: 36,
    startOfWarranty: "2023-05-15T10:00:00Z",
    endOfWarranty: "2026-05-15T10:00:00Z",
    warrantyConditions: "Garantie Constructeur",
    technician: "Jean Admin",
    supplier: "DistriCam",
    purchaseDate: "2023-04-20T10:00:00Z",
    history: [
      {
        id: "h-3-1",
        date: "2023-05-15T10:00:00Z",
        type: "installation",
        description: "Rackage et config IP",
        user: "Jean Admin",
      },
    ],
    documents: [],
    interventions: [],
  },
  {
    id: "eq-4",
    clientId: "c-clinique",
    clientName: "Clinique El Amel",
    siteId: "s-bat-a",
    siteName: "Bâtiment principal",
    address: "5 Route de l'Hôpital, 13009 Marseille",
    zone: "RDC",
    productId: "p-004",
    productName: "Switch PoE Cisco",
    productReference: "SW-CISCO-24",
    family: "Réseau",
    brand: "Cisco",
    model: "Catalyst 9200",
    serialNumber: "CIS-SW-4455",
    exactLocation: "Baie réseau RDC",
    status: "en_maintenance",
    installationDate: "2022-01-20T10:00:00Z",
    supplierWarranty: 12,
    clientWarranty: 24,
    startOfWarranty: "2022-01-20T10:00:00Z",
    endOfWarranty: new Date(
      now.getFullYear() - 1,
      now.getMonth(),
      now.getDate(),
    ).toISOString(),
    warrantyConditions: "Smartnet",
    technician: "Alex Net",
    supplier: "Cisco Partner",
    purchaseDate: "2021-12-05T10:00:00Z",
    history: [
      {
        id: "h-4-1",
        date: "2022-01-20T10:00:00Z",
        type: "installation",
        description: "Installation Switch PoE",
        user: "Alex Net",
      },
      {
        id: "h-4-2",
        date: now.toISOString(),
        type: "maintenance",
        description: "Mise à jour IOS planifiée",
        user: "Alex Net",
      },
    ],
    documents: [],
    interventions: [
      {
        id: "int-4-1",
        date: now.toISOString(),
        technician: "Alex Net",
        type: "maintenance",
        diagnostic: "Mise en conformité sécurité",
        result: "En cours d'application patch",
      },
    ],
  },
  {
    id: "eq-5",
    clientId: "c-banque",
    clientName: "Banque ABC",
    siteId: "s-agence-alger",
    siteName: "Agence Alger Centre",
    address: "Boulevard principal, Alger",
    zone: "Espace technique",
    productId: "p-005",
    productName: "Onduleur APC",
    productReference: "OND-APC-3000",
    family: "Énergie",
    brand: "APC",
    model: "Smart-UPS 3000",
    serialNumber: "APC-UPS-7788",
    exactLocation: "Salle serveur",
    status: "hors_service",
    installationDate: "2018-03-12T09:00:00Z",
    supplierWarranty: 24,
    clientWarranty: 24,
    startOfWarranty: "2018-03-12T09:00:00Z",
    endOfWarranty: new Date(
      now.getFullYear() - 2,
      now.getMonth(),
      now.getDate(),
    ).toISOString(),
    warrantyConditions: "Remplacement standard",
    technician: "Rachid Elec",
    supplier: "APC Direct",
    purchaseDate: "2018-02-15T10:00:00Z",
    history: [
      {
        id: "h-5-1",
        date: "2018-03-12T09:00:00Z",
        type: "installation",
        description: "Mise en service initiale",
        user: "Rachid Elec",
      },
      {
        id: "h-5-2",
        date: "2023-11-20T14:00:00Z",
        type: "panne",
        description: "Batteries HS",
        user: "Admin",
      },
      {
        id: "h-5-3",
        date: "2023-12-05T10:00:00Z",
        type: "retrait",
        description: "Déclaration hors service",
        user: "Admin",
      },
    ],
    documents: [],
    interventions: [],
  },
  {
    id: "eq-6",
    clientId: "c-usine",
    clientName: "Usine Nord",
    siteId: "s-entree",
    siteName: "Entrée employés",
    address: "ZI Nord, Lille 59000",
    zone: "Passage extérieur",
    productId: "p-006",
    productName: "Contrôleur d'accès ZKTeco",
    productReference: "ZKT-CTRL-10",
    family: "Contrôle d'accès",
    brand: "ZKTeco",
    model: "InBio260",
    serialNumber: "ZKT-INB-789",
    exactLocation: "Porte principale",
    status: "actif",
    installationDate: "2024-02-15T10:00:00Z",
    supplierWarranty: 24,
    clientWarranty: 24,
    startOfWarranty: "2024-02-15T10:00:00Z",
    endOfWarranty: "2026-02-15T10:00:00Z",
    warrantyConditions: "Sur site",
    technician: "Marc Dubois",
    supplier: "SecurityDist",
    purchaseDate: "2024-01-20T10:00:00Z",
    history: [
      {
        id: "h-6-1",
        date: "2024-02-15T10:00:00Z",
        type: "installation",
        description: "Câblage et pose ventouse",
        user: "Marc Dubois",
      },
    ],
    documents: [],
    interventions: [],
  },
  {
    id: "eq-7",
    clientId: "c-ecole",
    clientName: "École privée",
    siteId: "s-bloc",
    siteName: "Bloc pédagogique",
    address: "20 Avenue des Écoles, 69002 Lyon",
    zone: "Étage 2",
    productId: "p-007",
    productName: "Point d'accès Wi-Fi Ubiquiti",
    productReference: "UBNT-U6P",
    family: "Réseau sans fil",
    brand: "Ubiquiti",
    model: "U6-Pro",
    serialNumber: "UBNT-774A",
    exactLocation: "Étage 2 - Couloir",
    status: "remplace",
    installationDate: "2020-09-01T00:00:00Z",
    supplierWarranty: 12,
    clientWarranty: 12,
    startOfWarranty: "2020-09-01T00:00:00Z",
    endOfWarranty: new Date(
      now.getFullYear() - 3,
      now.getMonth(),
      now.getDate(),
    ).toISOString(),
    warrantyConditions: "Retour fournisseur",
    technician: "Luc Tech",
    supplier: "NetWifi",
    purchaseDate: "2020-08-15T10:00:00Z",
    history: [
      {
        id: "h-7-1",
        date: "2020-09-01T00:00:00Z",
        type: "installation",
        description: "Pose plafond",
        user: "Luc Tech",
      },
      {
        id: "h-7-2",
        date: "2024-02-15T10:00:00Z",
        type: "panne",
        description: "Perte signal 5GHz",
        user: "Support",
      },
      {
        id: "h-7-3",
        date: "2024-03-01T10:00:00Z",
        type: "remplacement",
        description: "Remplacé cause vétusté",
        user: "Luc Tech",
      },
    ],
    documents: [],
    interventions: [
      {
        id: "int-7-1",
        date: "2024-02-15T11:00:00Z",
        technician: "Luc Tech",
        type: "panne",
        diagnostic: "Défaut radio interne",
        result: "Installation nouvel équipement",
      },
    ],
  },
  {
    id: "eq-8",
    clientId: "c-logistique",
    clientName: "Société Logistique DZ",
    siteId: "s-siege",
    siteName: "Siège",
    address: "ZI Est, Lille",
    zone: "Baie principale",
    productId: "p-008",
    productName: "Firewall Fortinet",
    productReference: "FW-FTNT-60F",
    family: "Sécurité",
    brand: "Fortinet",
    model: "FortiGate 60F",
    serialNumber: "FGT-60F-991A",
    exactLocation: "Baie réseau principale",
    status: "actif",
    installationDate: "2023-10-10T09:00:00Z",
    supplierWarranty: 36,
    clientWarranty: 12,
    startOfWarranty: "2023-10-10T09:00:00Z",
    endOfWarranty: "2026-10-10T09:00:00Z",
    warrantyConditions: "FortiCare Premium",
    technician: "Tech Sécu",
    supplier: "SecurNet",
    purchaseDate: "2023-09-15T10:00:00Z",
    history: [
      {
        id: "h-8-1",
        date: "2023-10-10T09:00:00Z",
        type: "installation",
        description: "Installation, règles FW et VPN",
        user: "Tech Sécu",
      },
    ],
    documents: [],
    interventions: [],
  },
];
