import { ClientReturn } from './types';

export const MOCK_CLIENT_RETURNS: ClientReturn[] = [
  {
    id: "RET-2026-0001",
    returnNumber: "RET-2026-0001",
    clientName: "TechCorp",
    projectName: "Déploiement Serveurs",
    siteName: "Datacenter Paris",
    equipmentName: "Serveur Principal BD",
    productName: "Serveur rack DL380",
    productReference: "SRV-RACK-001",
    serialNumber: "SN-98754DF",
    deliveryNumber: "BL-2026-0089",
    technician: "Marc Dubois",
    reason: "Panne",
    returnType: "Défaut d'alimentation",
    warrantyStatus: "Sous garantie",
    requestDate: "2026-06-05",
    receptionDate: "",
    warehouseZone: "Zone d'attente",
    status: "En attente de réception",
    contactName: "Alice Martin",
    contactPhone: "+33 6 12 34 56 78",
    priority: "Haute",
    description: "Le serveur ne s'allume plus du tout. Le voyant d'alimentation reste rouge après plusieurs tentatives.",
    history: [
      { date: "2026-06-05T09:00:00", user: "Marc Dubois", action: "Création de la demande de retour" },
      { date: "2026-06-05T10:30:00", user: "Jean Admin", action: "Validation de la demande, en attente de réception" }
    ]
  },
  {
    id: "RET-2026-0002",

    returnNumber: "RET-2026-0002",
    clientName: "Global Construct",
    projectName: "Installation vidéosurveillance",
    siteName: "Chantier Lyon",
    equipmentName: "Caméra Ext PTZ 1",
    productName: "Caméra PTZ 4K",
    productReference: "CAM-PTZ-4K",
    serialNumber: "CAM-4K-098",
    deliveryNumber: "BL-2026-0034",
    technician: "Sophie Martin",
    reason: "Produit défectueux",
    returnType: "Défaut optique",
    warrantyStatus: "Sous garantie",
    requestDate: "2026-06-01",
    receptionDate: "2026-06-03",
    warehouseZone: "Quarantaine",
    status: "En diagnostic",
    contactName: "Benoît Legrand",
    contactPhone: "+33 6 98 76 54 32",
    priority: "Moyenne",
    description: "L'image est floue même après nettoyage de la lentille. Le focus automatique semble cassé.",
    receptionPhysical: { date: "2026-06-03T14:15:00", receivedBy: "Paul Magasinier", realCondition: "Lentille rayée, boîtier intact", qty: 1, accessories: "Caméra seule, sans câble", packaging: false, discrepancies: "Manque le câble Ethernet PoE" },
    diagnostic: { technician: "Sophie Martin", date: "2026-06-04", symptoms: "Focus impossible", tests: "Test optique, test moteur focus", probableCause: "Moteur autofocus HS", parts: "Bloc optique", conclusion: "À remplacer", warrantyCoverage: "Pris en charge" },
    history: [
      { date: "2026-06-01T10:00:00", user: "Sophie Martin", action: "Création de la demande" },
      { date: "2026-06-03T14:15:00", user: "Paul Magasinier", action: "Réception physique de l'équipement" },
      { date: "2026-06-04T09:00:00", user: "Sophie Martin", action: "Début du diagnostic" }
    ]
  },
  {
    id: "RET-2026-0003",
    returnNumber: "RET-2026-0003",
    clientName: "Boutique Paris",
    projectName: "Mise à jour TPE",
    siteName: "Magasin C",
    equipmentName: "TPE Caisse Avant",
    productName: "Terminal de paiement Y",
    productReference: "TPE-Y-789",
    serialNumber: "TPE-Y-888-21",
    deliveryNumber: "BL-2026-0012",
    technician: "Lucas Dupont",
    reason: "Demande de diagnostic",
    returnType: "Erreur lecture matérielle",
    warrantyStatus: "Hors garantie",
    requestDate: "2026-05-20",
    receptionDate: "2026-05-22",
    warehouseZone: "Atelier Réparation",
    status: "Réparation en cours",
    contactName: "Claire Dubois",
    contactPhone: "+33 1 23 45 67 89",
    priority: "Moyenne",
    description: "Le TPE affiche 'Erreur matérielle' à l'insertion de certaines cartes.",
    receptionPhysical: { date: "2026-05-22T09:30:00", receivedBy: "Paul Magasinier", realCondition: "Bon état, rayure sur l'écran", qty: 1, accessories: "Chargeur inclus", packaging: true, discrepancies: "Aucun écart" },
    diagnostic: { technician: "Lucas Dupont", date: "2026-05-23", symptoms: "Erreur lecture puce", tests: "Test cartes de référence", probableCause: "Lecteur de carte encrassé ou contacts tordus", parts: "Bloc lecteur carte", conclusion: "Réparable", warrantyCoverage: "Hors garantie" },
    decision: { type: "Réparer l'équipement", responsible: "Jean Admin", expectedDate: "2026-06-10", cost: "85.00 €", comment: "Devis validé par le client.", replacementSerialNumber: "" },
    history: [
      { date: "2026-05-20T11:00:00", user: "Lucas Dupont", action: "Création de la demande" },
      { date: "2026-05-22T09:30:00", user: "Paul Magasinier", action: "Réception physique de l'équipement" },
      { date: "2026-05-23T14:00:00", user: "Lucas Dupont", action: "Diagnostic terminé" },
      { date: "2026-05-25T10:00:00", user: "Jean Admin", action: "Validation du devis et début de réparation" }
    ]
  },
  {
    id: "RET-2026-0004",
    returnNumber: "RET-2026-0004",
    clientName: "Industrie Plus",
    projectName: "Réseau principal",
    siteName: "Usine Annexe",
    equipmentName: "Switch 48 ports",
    productName: "Switch Gigabit 48P",
    productReference: "SW-48-GB",
    serialNumber: "SW48-ABC-123",
    deliveryNumber: "BL-2026-0045",
    technician: "Jean Admin",
    reason: "Remplacement",
    returnType: "Garantie échange",
    warrantyStatus: "Sous garantie",
    requestDate: "2026-05-15",
    receptionDate: "2026-05-18",
    warehouseZone: "Entrepôt de retour",
    status: "Clôturé",
    contactName: "Jacques Moreau",
    contactPhone: "+33 6 11 22 33 44",
    priority: "Haute",
    description: "Ports 1 à 12 inactifs suite à un orage.",
    receptionPhysical: { date: "2026-05-18T10:00:00", receivedBy: "Paul Magasinier", realCondition: "Odeur de brûlé", qty: 1, accessories: "Sans cordon d'alimentation", packaging: false, discrepancies: "Aucun écart" },
    diagnostic: { technician: "Jean Admin", date: "2026-05-19", symptoms: "Ports HS", tests: "Test loopback", probableCause: "Surtension", parts: "Carte mère", conclusion: "Irréparable", warrantyCoverage: "Pris en charge" },
    decision: { type: "Remplacer l'équipement", responsible: "Jean Admin", expectedDate: "2026-05-20", cost: "0.00 €", comment: "Échange standard sous garantie constructeur.", replacementSerialNumber: "SW48-XYZ-999" },
    history: [
      { date: "2026-05-15T15:00:00", user: "Jean Admin", action: "Création de la demande" },
      { date: "2026-05-18T10:00:00", user: "Paul Magasinier", action: "Réception physique de l'équipement" },
      { date: "2026-05-19T11:00:00", user: "Jean Admin", action: "Diagnostic terminé, irréparable" },
      { date: "2026-05-20T09:00:00", user: "Jean Admin", action: "Remplacement effectué et matériel expédié" },
      { date: "2026-05-22T14:00:00", user: "Jean Admin", action: "Clôture du retour suite à confirmation de réception du client" }
    ]
  }
];
