import { SerialNumber } from "./types";

export const mockSerialNumbers: SerialNumber[] = [
  {
    id: "sn-1",
    serial: "SN-HIK-00101",
    productId: "p-001",
    productName: "Caméra Dôme IP 4MP Hikvision",
    productReference: "HIK-CAM-001",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-2CD2143G0-I",
    status: "en_stock",
    location: "Dépôt principal",
    warehouse: "Dépôt principal (Paris)",
    exactLocation: "Allée A, Rayon 3, Étagère 2",
    startOfWarranty: "2023-11-20T00:00:00Z",
    endOfWarranty: "2026-11-20T00:00:00Z",
    warrantyConditions:
      "Garantie constructeur standard 3 ans. Remplacement anticipé sous 48h.",
    dateOfPurchase: "2023-11-20T00:00:00Z",
    dateOfEntry: "2023-11-25T00:00:00Z",
    supplier: "Hikvision France",
    history: [
      {
        id: "h1",
        date: "2023-11-25T10:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Marc Tech",
        documentRef: "doc-rec-1",
      },
    ],
    documents: [
      {
        id: "doc-fac-1",
        name: "Facture_HIK_20231120.pdf",
        type: "invoice",
        date: "2023-11-20T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-rec-1",
        name: "Bon_Reception_BR-2023-11-042.pdf",
        type: "delivery_note",
        date: "2023-11-25T00:00:00Z",
        url: "#",
      },
    ],
  },
  {
    id: "sn-2",
    serial: "SN-HIK-00102",
    productId: "p-001",
    productName: "Caméra Dôme IP 4MP Hikvision",
    productReference: "HIK-CAM-001",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-2CD2143G0-I",
    status: "reserve",
    location: "Dépôt principal",
    warehouse: "Dépôt principal (Paris)",
    exactLocation: "Zone de préparation de commandes",
    clientSite: "Chantier Hôtel X",
    startOfWarranty: "2023-11-20T00:00:00Z",
    endOfWarranty: "2026-11-20T00:00:00Z",
    warrantyConditions: "Garantie constructeur standard 3 ans.",
    dateOfPurchase: "2023-11-20T00:00:00Z",
    dateOfEntry: "2023-11-25T00:00:00Z",
    supplier: "Hikvision France",
    history: [
      {
        id: "h2",
        date: "2023-11-26T14:30:00Z",
        type: "reservation",
        description: "Réservé pour Chantier Hôtel X (Projet PRJ-23-014)",
        user: "Jean Dupont",
      },
      {
        id: "h1",
        date: "2023-11-25T10:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Marc Tech",
        documentRef: "doc-rec-1",
      },
    ],
    documents: [
      {
        id: "doc-fac-1",
        name: "Facture_HIK_20231120.pdf",
        type: "invoice",
        date: "2023-11-20T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-rec-1",
        name: "Bon_Reception_BR-2023-11-042.pdf",
        type: "delivery_note",
        date: "2023-11-25T00:00:00Z",
        url: "#",
      },
    ],
  },
  {
    id: "sn-3",
    serial: "CISCO-SW-24-998",
    productId: "p-002",
    productName: "Switch Cisco 24 ports PoE+",
    productReference: "CISCO-SW-24P",
    family: "Réseau",
    brand: "Cisco",
    model: "Catalyst C1000-24P-4G-L",
    status: "installe_client",
    location: "Site Client",
    clientSite: "Mairie de Paris - Bâtiment A",
    exactLocation: "Baie Réseau Principal, U12",
    startOfWarranty: "2022-05-10T00:00:00Z",
    endOfWarranty: "2025-05-15T00:00:00Z",
    endOfClientWarranty: "2023-06-01T00:00:00Z", // 1 an pour le client
    warrantyConditions: "Garantie constructeur 3 ans.",
    dateOfPurchase: "2022-05-10T00:00:00Z",
    dateOfEntry: "2022-05-15T00:00:00Z",
    dateOfInstallation: "2022-06-01T00:00:00Z",
    supplier: "Cisco Partner Europe",
    history: [
      {
        id: "h3",
        date: "2022-06-01T09:00:00Z",
        type: "installation",
        description: "Installé sur site, Bâtiment A",
        user: "Luc Tech",
        documentRef: "doc-pv-1",
      },
      {
        id: "h2",
        date: "2022-05-20T11:00:00Z",
        type: "transfert",
        description: "Transfert vers véhicule",
        user: "Luc Tech",
        documentRef: "doc-trans-1",
      },
      {
        id: "h1",
        date: "2022-05-15T10:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Marc Tech",
      },
    ],
    documents: [
      {
        id: "doc-fac-2",
        name: "Fac_Cisco_MAY22.pdf",
        type: "invoice",
        date: "2022-05-10T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-trans-1",
        name: "Bon_Transfert_BT-2022-04.pdf",
        type: "exit_note",
        date: "2022-05-20T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-pv-1",
        name: "PV_Installation_MairieParis.pdf",
        type: "installation_pv",
        date: "2022-06-01T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-photo-1",
        name: "Baie_Reseau_A.jpg",
        type: "photo",
        date: "2022-06-01T00:00:00Z",
        url: "#",
      },
    ],
  },
  {
    id: "sn-4",
    serial: "SN-HIK-00105",
    productId: "p-001",
    productName: "Caméra Dôme IP 4MP Hikvision",
    productReference: "HIK-CAM-001",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-2CD2143G0-I",
    status: "en_panne",
    location: "Atelier",
    exactLocation: "Étagère Diagnostic, Casier 4",
    clientSite: "Mairie de Paris - Bâtiment B (Retiré)",
    startOfWarranty: "2023-11-20T00:00:00Z",
    endOfWarranty: "2026-11-20T00:00:00Z",
    warrantyConditions: "Garantie constructeur standard 3 ans.",
    dateOfPurchase: "2023-11-20T00:00:00Z",
    dateOfEntry: "2023-11-25T00:00:00Z",
    supplier: "Hikvision France",
    history: [
      {
        id: "h4",
        date: "2023-12-06T10:00:00Z",
        type: "retour",
        description: "Retour en atelier pour diagnostic",
        user: "Sam Tech",
      },
      {
        id: "h3",
        date: "2023-12-05T15:00:00Z",
        type: "panne",
        description: "Déclaré en panne suite pb infrarouge",
        user: "Sam Tech",
        documentRef: "doc-rap-1",
      },
      {
        id: "h2",
        date: "2023-11-30T09:00:00Z",
        type: "installation",
        description: "Installé sur site",
        user: "Sam Tech",
        documentRef: "doc-pv-2",
      },
      {
        id: "h1",
        date: "2023-11-25T10:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Marc Tech",
      },
    ],
    documents: [
      {
        id: "doc-pv-2",
        name: "PV_Instal_MairieB.pdf",
        type: "installation_pv",
        date: "2023-11-30T00:00:00Z",
        url: "#",
      },
      {
        id: "doc-rap-1",
        name: "Rapport_Intervention_R-1452.pdf",
        type: "intervention_report",
        date: "2023-12-05T00:00:00Z",
        url: "#",
      },
    ],
  },
  {
    id: "sn-5",
    serial: "APC-1500-A88",
    productId: "p-003",
    productName: "Onduleur APC Smart-UPS",
    productReference: "APC-UPS-1500",
    family: "Énergie",
    brand: "APC",
    model: "SMT1500C",
    status: "installe_client",
    location: "Site Client",
    clientSite: "Hôtel Splendid",
    exactLocation: "Local technique Sous-sol",
    startOfWarranty: "2021-06-01T00:00:00Z",
    endOfWarranty: "2024-06-10T00:00:00Z", // Bientôt expiré ou expiré
    warrantyConditions: "Garantie 3 ans incluant batteries.",
    dateOfPurchase: "2021-06-01T00:00:00Z",
    dateOfEntry: "2021-06-05T00:00:00Z",
    dateOfInstallation: "2021-06-10T00:00:00Z",
    supplier: "TechData",
    history: [
      {
        id: "h1",
        date: "2021-06-05T10:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Marc Tech",
      },
      {
        id: "h2",
        date: "2021-06-10T09:00:00Z",
        type: "installation",
        description: "Installé sur site",
        user: "Jean Dupont",
      },
    ],
    documents: [],
  },
  {
    id: "sn-6",
    serial: "NVR-HIK-A99B2",
    productId: "p-007",
    productName: "NVR Hikvision 16 Canaux",
    productReference: "HIK-NVR-16CH",
    family: "Vidéosurveillance",
    brand: "Hikvision",
    model: "DS-7616NI-I2/16P",
    status: "retour_fournisseur",
    location: "Chez Fournisseur",
    supplier: "DistriCam Europe",
    startOfWarranty: "2023-05-15T00:00:00Z",
    endOfWarranty: "2026-05-15T00:00:00Z",
    history: [
      {
        id: "h3",
        date: "2023-11-20T14:00:00Z",
        type: "retour_fournisseur",
        description: "Envoi RMA pour ports PoE défectueux (RMA#9902)",
        user: "SAV Tech",
      },
      {
        id: "h2",
        date: "2023-11-18T10:00:00Z",
        type: "panne",
        description: "Ports 5 à 8 HS",
        user: "SAV Tech",
      },
      {
        id: "h1",
        date: "2023-05-20T10:00:00Z",
        type: "entree",
        description: "Réception initiale",
        user: "Marc Tech",
      },
    ],
  },
  {
    id: "sn-7",
    serial: "WAP-UBNT-774A",
    productId: "p-018",
    productName: "Point d'accès Ubiquiti UniFi U6-Pro",
    productReference: "U6-PRO",
    family: "Réseau sans fil",
    brand: "Ubiquiti",
    model: "U6-Pro",
    status: "remplace",
    location: "Atelier (Mise au rebut)",
    clientSite: "Campus Supérieur Descartes (Ancien)",
    exactLocation: "Bâtiment B - Amphi 2",
    startOfWarranty: "2020-09-01T00:00:00Z",
    endOfWarranty: "2021-09-01T00:00:00Z", // expiré
    history: [
      {
        id: "h4",
        date: "2024-02-15T11:00:00Z",
        type: "remplacement",
        description: "Remplacé cause vétusté",
        user: "Tech Réseau",
      },
      {
        id: "h3",
        date: "2024-02-15T10:00:00Z",
        type: "panne",
        description: "Plus de signal 5GHz",
        user: "Tech Réseau",
      },
      {
        id: "h2",
        date: "2020-09-15T14:00:00Z",
        type: "installation",
        description: "Installé au plafond",
        user: "Jean Dupont",
      },
      {
        id: "h1",
        date: "2020-09-05T09:00:00Z",
        type: "entree",
        description: "Réception fournisseur",
        user: "Luc Tech",
      },
    ],
  },
  {
    id: "sn-8",
    serial: "FW-FORTI-60F-X91",
    productId: "p-019",
    productName: "Firewall Fortinet FortiGate 60F",
    productReference: "FG-60F",
    family: "Sécurité réseau",
    brand: "Fortinet",
    model: "FG-60F",
    status: "en_reparation",
    location: "Centre de réparation externe",
    clientSite: "Cabinet d'Avocats X",
    startOfWarranty: "2023-01-15T00:00:00Z",
    endOfWarranty: "2026-01-15T00:00:00Z",
    history: [
      {
        id: "h3",
        date: "2024-03-01T09:00:00Z",
        type: "en_reparation",
        description: "Envoyé au centre pour pb alim",
        user: "SAV Tech",
      },
      {
        id: "h2",
        date: "2024-02-28T16:00:00Z",
        type: "retour",
        description: "Apporté à l'atelier suite intervention",
        user: "Tech Sécu",
      },
      {
        id: "h1",
        date: "2023-02-01T10:00:00Z",
        type: "installation",
        description: "Installé et configuré",
        user: "Tech Sécu",
      },
    ],
  },
  {
    id: "sn-9",
    serial: "SVR-DELL-P440-Z1",
    productId: "p-006",
    productName: "Serveur Dell PowerEdge R440",
    productReference: "DELL-R440-SVR",
    family: "Serveurs",
    brand: "Dell",
    model: "R440",
    status: "affecte_chantier",
    location: "Atelier Intégration",
    warehouse: "Dépôt principal (Paris)",
    exactLocation: "Banc de test #2",
    clientSite: "Clinique Santé Plus",
    startOfWarranty: "2024-05-10T00:00:00Z",
    endOfWarranty: "2027-05-10T00:00:00Z",
    history: [
      {
        id: "h2",
        date: "2024-05-20T08:00:00Z",
        type: "transfert",
        description: "Banc de test",
        user: "Tech Système",
      },
      {
        id: "h1",
        date: "2024-05-15T11:00:00Z",
        type: "entree",
        description: "Réception",
        user: "Marc Tech",
      },
    ],
  },
  {
    id: "sn-10",
    serial: "CAM-ANALOG-OLD-01",
    productId: "p-016",
    productName: "Caméra dôme 720p",
    productReference: "CAM-OLD-720P",
    family: "CCTV",
    brand: "Generic",
    model: "Dome-720",
    status: "hors_service",
    location: "DEEE",
    exactLocation: "Bac de recyclage",
    clientSite: "Résidence Les Pins (Ancien)",
    startOfWarranty: "2015-02-01T00:00:00Z",
    endOfWarranty: "2016-02-01T00:00:00Z",
    history: [
      {
        id: "h3",
        date: "2024-01-10T14:00:00Z",
        type: "mise_hors_service",
        description: "Mise au rebut",
        user: "Admin",
      },
      {
        id: "h2",
        date: "2023-12-15T10:00:00Z",
        type: "retour",
        description: "Démonté du site",
        user: "Tech Chantier",
      },
      {
        id: "h1",
        date: "2015-03-01T09:00:00Z",
        type: "installation",
        description: "Installé",
        user: "Tech Ancien",
      },
    ],
  },
];
