import { CommandeFournisseur } from './types';

export const MOCK_COMMANDES_FOURNISSEUR: CommandeFournisseur[] = [
  {
    id: 'cmd-001',
    reference: 'CF-2026-001',
    fournisseurId: 'f1',
    fournisseurName: 'Hikvision Algérie',
    dateCommande: '2026-05-15',
    dateLivraisonPrevue: '2026-06-10',
    responsableId: 'u1',
    responsableName: 'Amine Manager',
    statut: 'Partiellement reçue',
    commentaire: 'Commande mensuelle de réapprovisionnement CCTV.',
    lignes: [
      {
        id: 'l1',
        productId: 'p1',
        productName: 'Caméra IP Dôme 4K',
        refFournisseur: 'HIK-CAM-4K',
        qteCmd: 50,
        qteRecue: 30,
        prixU: 12500,
      },
      {
        id: 'l2',
        productId: 'p2',
        productName: 'NVR 16 Voies PoE',
        refFournisseur: 'HIK-NVR-16P',
        qteCmd: 5,
        qteRecue: 0,
        prixU: 45000,
      }
    ],
    receptionId: 'rec-001',
    modePaiement: 'Virement bancaire (30 jours)',
    devise: 'DZD',
    remise: 5,
    fraisLivraison: 2500,
    conditionsParticulieres: 'Livraison au dépôt principal impérative avant 14h.',
    createdAt: '2026-05-15T09:30:00Z',
    updatedAt: '2026-05-25T14:20:00Z',
  },
  {
    id: 'cmd-002',
    reference: 'CF-2026-002',
    fournisseurId: 'f2',
    fournisseurName: 'TechDistribution DZ (TP-Link)',
    dateCommande: '2026-05-20',
    dateLivraisonPrevue: '2026-05-28',
    responsableId: 'u2',
    responsableName: 'Sarah Logistique',
    statut: 'Envoyée', // wait, the user asked for statuts: brouillon, validée, envoyée, partiellement reçue, reçue, annulée. And "commande avec retard" as a filter. So we keep statut as "Envoyée" and dateLivraisonPrevue in the past = En retard. Wait, let's keep statut valid.
    commentaire: 'Urgent pour projet Banque.',
    lignes: [
      {
        id: 'l3',
        productId: 'p3',
        productName: 'Switch 24 Ports Gigabit PoE+',
        refFournisseur: 'TPL-SW-24P',
        qteCmd: 10,
        qteRecue: 0,
        prixU: 32000,
      }
    ],
    modePaiement: 'Paiement à la livraison',
    devise: 'DZD',
    remise: 0,
    fraisLivraison: 0,
    conditionsParticulieres: 'Appeler le livreur 1h avant.',
    createdAt: '2026-05-20T10:15:00Z',
    updatedAt: '2026-05-21T09:00:00Z',
  },
  {
    id: 'cmd-003',
    reference: 'CF-2026-003',
    fournisseurId: 'f3',
    fournisseurName: 'APC by Schneider',
    dateCommande: '2026-06-01',
    dateLivraisonPrevue: '2026-06-15',
    responsableId: 'u1',
    responsableName: 'Amine Manager',
    statut: 'Validée',
    commentaire: 'Onduleurs pour baies de brassage.',
    lignes: [
      {
        id: 'l4',
        productId: 'p4',
        productName: 'Onduleur Smart-UPS 1500VA',
        refFournisseur: 'APC-SMT1500',
        qteCmd: 8,
        qteRecue: 0,
        prixU: 85000,
      }
    ],
    modePaiement: 'LC',
    devise: 'EUR',
    remise: 10,
    fraisLivraison: 150, // EUR
    conditionsParticulieres: 'Incoterm CIF Alger.',
    createdAt: '2026-06-01T11:00:00Z',
    updatedAt: '2026-06-02T10:00:00Z',
  },
  {
    id: 'cmd-004',
    reference: 'CF-2026-004',
    fournisseurId: 'f4',
    fournisseurName: 'Dell Technologies',
    dateCommande: '2026-05-25',
    dateLivraisonPrevue: '2026-07-25',
    responsableId: 'u1',
    responsableName: 'Amine Manager',
    statut: 'Brouillon',
    commentaire: 'Serveurs pour le nouveau datacenter.',
    lignes: [
      {
        id: 'l5',
        productId: 'p5',
        productName: 'Serveur PowerEdge R750',
        refFournisseur: 'DELL-R750',
        qteCmd: 2,
        qteRecue: 0,
        prixU: 450000,
      }
    ],
    modePaiement: 'Virement bancaire (60 jours)',
    devise: 'USD',
    remise: 0,
    fraisLivraison: 500,
    conditionsParticulieres: 'Garantie ProSupport Plus 5 ans incluse.',
    createdAt: '2026-05-25T14:30:00Z',
    updatedAt: '2026-05-25T14:45:00Z',
  },
  {
    id: 'cmd-005',
    reference: 'CF-2026-005',
    fournisseurId: 'f5',
    fournisseurName: 'MikroTik Latvia',
    dateCommande: '2026-05-10',
    dateLivraisonPrevue: '2026-05-25',
    responsableId: 'u2',
    responsableName: 'Sarah Logistique',
    statut: 'Reçue',
    commentaire: 'Routeurs pour déploiement fibre.',
    lignes: [
      {
        id: 'l6',
        productId: 'p6',
        productName: 'Routeur Cloud Core CCR2004',
        refFournisseur: 'MT-CCR2004',
        qteCmd: 15,
        qteRecue: 15,
        prixU: 85000,
      }
    ],
    receptionId: 'rec-005',
    modePaiement: 'Virement international',
    devise: 'EUR',
    remise: 15,
    fraisLivraison: 200,
    conditionsParticulieres: 'Expédition par DHL express.',
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-05-26T16:00:00Z',
  },
  {
    id: 'cmd-006',
    reference: 'CF-2026-006',
    fournisseurId: 'f2',
    fournisseurName: 'TechDistribution DZ (TP-Link)',
    dateCommande: '2026-04-10',
    dateLivraisonPrevue: '2026-04-20',
    responsableId: 'u3',
    responsableName: 'Karim Achats',
    statut: 'Annulée',
    commentaire: 'Erreur de référence, remplacée par CF-2026-002.',
    lignes: [
      {
        id: 'l7',
        productId: 'p7',
        productName: 'Switch 16 Ports',
        refFournisseur: 'TPL-SW-16P',
        qteCmd: 10,
        qteRecue: 0,
        prixU: 15000,
      }
    ],
    modePaiement: 'Chèque',
    devise: 'DZD',
    remise: 0,
    fraisLivraison: 0,
    conditionsParticulieres: '',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-11T10:00:00Z',
  }
];
