import { StockLocation } from "./types";

export const MOCK_LOCATIONS: StockLocation[] = [
  {
    id: "loc1",
    reference: "DEP-MAIN",
    name: "Dépôt Principal",
    type: "Dépôt",
    address: "Zone Industrielle Ouest",
    city: "Alger",
    manager: "K. Samia",
    status: "Actif",
    maxCapacity: 5000,
    usedCapacity: 3450,
    capacityUnit: "pièces",
    alertThreshold: 4500,
    createdAt: "2023-01-10",
    description: "Entrepôt principal pour le stockage des équipements volumineux et du stock tampon.",
    productsStoredCount: 156,
    hasSerializedProducts: true,
    hierarchy: { depot: "Dépôt Principal" },
    products: [
      { id: "p1", reference: "CAM-HIK-2CD2043", name: "Caméra IP Hikvision DS-2CD2043", physicalQuantity: 45, reservedQuantity: 5, availableQuantity: 40, isSerialized: true },
      { id: "p2", reference: "NVR-HIK-16CH", name: "NVR Hikvision 16 canaux", physicalQuantity: 8, reservedQuantity: 3, availableQuantity: 5, isSerialized: true },
      { id: "p4", reference: "ROUT-MIK-4011", name: "Routeur MikroTik RB4011", physicalQuantity: 12, reservedQuantity: 2, availableQuantity: 10, isSerialized: true }
    ],
    movements: [
      { id: "m1", type: "Entrée", date: "2026-06-01", productName: "Caméra IP Hikvision DS-2CD2043", quantity: 20, user: "K. Samia" },
      { id: "m2", type: "Sortie", date: "2026-06-02", productName: "NVR Hikvision 16 canaux", quantity: 1, user: "M. Ahmed" }
    ],
    history: [
      { id: "h1", date: "2026-06-01", type: "Inventaire", title: "Inventaire mensuel validé", user: "K. Samia" },
      { id: "h2", date: "2026-05-15", type: "MAJ", title: "Capacité maximale ajustée", user: "Admin" }
    ]
  },
  {
    id: "loc2",
    reference: "ZONE-NET",
    name: "Zone Réseau",
    type: "Zone",
    parentLocation: "Dépôt Principal",
    parentLocationId: "loc1",
    manager: "A. Karim",
    status: "Actif",
    maxCapacity: 1000,
    usedCapacity: 950,
    capacityUnit: "pièces",
    alertThreshold: 900,
    createdAt: "2023-01-15",
    description: "Zone dédiée aux switches, routeurs et serveurs.",
    productsStoredCount: 42,
    hasSerializedProducts: true,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone Réseau" }
  },
  {
    id: "loc3",
    reference: "ZONE-CCTV",
    name: "Zone CCTV",
    type: "Zone",
    parentLocation: "Dépôt Principal",
    parentLocationId: "loc1",
    manager: "A. Karim",
    status: "Saturé",
    maxCapacity: 800,
    usedCapacity: 800,
    capacityUnit: "pièces",
    alertThreshold: 750,
    createdAt: "2023-01-15",
    description: "Zone dédiée aux caméras et enregistreurs.",
    productsStoredCount: 85,
    hasSerializedProducts: true,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone CCTV" }
  },
  {
    id: "loc4",
    reference: "ALLEE-A",
    name: "Allée A",
    type: "Allée",
    parentLocation: "Zone Réseau",
    parentLocationId: "loc2",
    manager: "S. Malik",
    status: "Actif",
    maxCapacity: 200,
    usedCapacity: 50,
    capacityUnit: "cartons",
    alertThreshold: 180,
    createdAt: "2023-02-01",
    description: "Allée principale de la zone réseau.",
    productsStoredCount: 12,
    hasSerializedProducts: false,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone Réseau", allee: "Allée A" }
  },
  {
    id: "loc5",
    reference: "RAYON-3",
    name: "Rayon 3",
    type: "Rayon",
    parentLocation: "Allée A",
    parentLocationId: "loc4",
    manager: "S. Malik",
    status: "Actif",
    maxCapacity: 50,
    usedCapacity: 12,
    capacityUnit: "pièces",
    alertThreshold: 45,
    createdAt: "2023-02-05",
    description: "Stockage des petits switches.",
    productsStoredCount: 5,
    hasSerializedProducts: true,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone Réseau", allee: "Allée A", rayon: "Rayon 3" }
  },
  {
    id: "loc6",
    reference: "ETAG-2",
    name: "Étagère 2",
    type: "Étagère",
    parentLocation: "Rayon 3",
    parentLocationId: "loc5",
    manager: "S. Malik",
    status: "Actif",
    maxCapacity: 10,
    usedCapacity: 0,
    capacityUnit: "pièces",
    alertThreshold: 8,
    createdAt: "2023-02-10",
    description: "Position de stockage individuelle.",
    productsStoredCount: 0,
    hasSerializedProducts: false,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone Réseau", allee: "Allée A", rayon: "Rayon 3", etagere: "Étagère 2" }
  },
  {
    id: "loc7",
    reference: "RET-FOU",
    name: "Zone Retour Fournisseur",
    type: "Zone retour",
    parentLocation: "Dépôt Principal",
    parentLocationId: "loc1",
    manager: "K. Samia",
    status: "Actif",
    maxCapacity: 100,
    usedCapacity: 15,
    capacityUnit: "pièces",
    alertThreshold: 80,
    createdAt: "2023-03-20",
    description: "Articles en attente d'enlèvement par les fournisseurs.",
    productsStoredCount: 4,
    hasSerializedProducts: true,
    hierarchy: { depot: "Dépôt Principal", zone: "Zone Retour Fournisseur" }
  },
  {
    id: "loc8",
    reference: "ZONE-SAV",
    name: "Zone SAV",
    type: "Zone SAV",
    manager: "T. Mourad",
    status: "Actif",
    maxCapacity: 200,
    usedCapacity: 45,
    capacityUnit: "pièces",
    alertThreshold: 180,
    createdAt: "2023-04-15",
    description: "Matériel client en cours de diagnostic ou répartion.",
    productsStoredCount: 22,
    hasSerializedProducts: true,
    hierarchy: { zone: "Zone SAV" }
  },
  {
    id: "loc9",
    reference: "VEH-TECH-A",
    name: "Véhicule Technicien A",
    type: "Véhicule",
    manager: "Y. Sofiane",
    status: "Actif",
    maxCapacity: 50,
    usedCapacity: 38,
    capacityUnit: "pièces",
    alertThreshold: 45,
    createdAt: "2024-01-10",
    description: "Stock embarqué pour les interventions quotidiennes.",
    productsStoredCount: 14,
    hasSerializedProducts: true,
    hierarchy: { zone: "Véhicule Technicien A" }
  },
  {
    id: "loc10",
    reference: "VEH-TECH-B",
    name: "Véhicule Technicien B",
    type: "Véhicule",
    manager: "L. Hocine",
    status: "Maintenance",
    maxCapacity: 50,
    usedCapacity: 10,
    capacityUnit: "pièces",
    alertThreshold: 45,
    createdAt: "2024-01-10",
    description: "Véhicule en révision, stock minimum conservé.",
    productsStoredCount: 3,
    hasSerializedProducts: false,
    hierarchy: { zone: "Véhicule Technicien B" }
  },
  {
    id: "loc11",
    reference: "CHAN-SONA",
    name: "Chantier Client Sonatrach",
    type: "Chantier",
    address: "Hassi Messaoud",
    city: "Ouargla",
    manager: "R. Amine",
    status: "Actif",
    maxCapacity: 300,
    usedCapacity: 245,
    capacityUnit: "pièces",
    alertThreshold: 280,
    createdAt: "2024-05-20",
    description: "Stock déporté pour le projet d'installation de sécurité.",
    productsStoredCount: 35,
    hasSerializedProducts: true,
    hierarchy: { zone: "Chantier Client Sonatrach" }
  }
];
